# fly.toml app configuration file generated for nuxfly-test2 on 2025-07-12T19:23:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nuxfly-test2'
primary_region = 'iad'

[experimental]
  exec = ['sh', '/start.sh']

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'sqlite_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 500
    soft_limit = 400

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/public/_fonts'
  url_prefix = '/_fonts'

[[statics]]
  guest_path = '/app/public/_nuxt'
  url_prefix = '/_nuxt'

[[statics]]
  guest_path = '/app/public/favicon.ico'
  url_prefix = '/favicon.ico'
